### ISSUE TITLE
Make does not like the DRGB_SLOWDOWN_GPIO flag

### ISSUE THREAD

**Issue by westonal** [hzeller/rpi-rgb-led-matrix#1147]
`make HARDWARE_DESC=adafruit-hat USER_DEFINES="-DRGB_SLOWDOWN_GPIO=2 -DDISABLE_HARDWARE_PULSES"`

```
pi@raspberrypi:~/my-led $ make HARDWARE_DESC=adafruit-hat USER_DEFINES="-DRGB_SLOWDOWN_GPIO=2 -DDISABLE_HARDWARE_PULSES"
make -C ./lib
make[1]: Entering directory '/home/pi/my-led/lib'
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC -DRGB_SLOWDOWN_GPIO=2 -DDISABLE_HARDWARE_PULSES -DDEFAULT_HARDWARE='"adafruit-hat"' -fno-exceptions -std=c++11 -c -o gpio.o gpio.cc
In file included from gpio.cc:19:
gpio.h:39:7: error: expected identifier before ‘)’ token
       );
       ^
gpio.h:33:8: error: default argument missing for parameter 2 of ‘bool rgb_matrix::GPIO::Init(int, int)’
   bool Init(int
        ^~~~
gpio.cc:337:6: error: no declaration matches ‘bool rgb_matrix::GPIO::Init(int)’
 bool GPIO::Init(int slowdown) {
      ^~~~
In file included from gpio.cc:19:
gpio.h:33:8: note: candidate is: ‘bool rgb_matrix::GPIO::Init(int, int)’
   bool Init(int
        ^~~~
gpio.h:27:7: note: ‘class rgb_matrix::GPIO’ defined here
 class GPIO {
       ^~~~
make[1]: *** [Makefile:185: gpio.o] Error 1
make[1]: Leaving directory '/home/pi/my-led/lib'
make: *** [Makefile:15: lib/librgbmatrix.a] Error 2
```

Also I see from this script: https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/rgb-matrix.sh
that there should be an option to compile in the rows and cols with `-DLED_COLS` and `-DLED_ROWS`, did that get removed?

**Comment by hzeller** [comment]
Fixed the slowdown compile error. This slipped because these days all these settings are done at runtime when you initialize the matrix.

I don't remember to ever have had `COLS` and `ROWS` defines, but maybe Adafruit had in their fork ? The cols and rows are defined at runtime when you set the options or using the convenient command line flags (see the examples in `examples-api-use/ `, e.g. the [`minimal-example.cc`](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/examples-api-use/minimal-example.cc#L47) ).
