### ISSUE TITLE
When I run video-viewer, the LED panel does not display.

### ISSUE THREAD

**Issue by 6010110254** [hzeller/rpi-rgb-led-matrix#1164]
i see from >> https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/utils
i have video name avenger2.webm  1 minute
![Screenshot (25)](https://user-images.githubusercontent.com/47842161/94474809-5b499c00-01f8-11eb-958e-3dc2d834f4ad.png)
![Screenshot (23)](https://user-images.githubusercontent.com/47842161/94474811-5c7ac900-01f8-11eb-917c-aea63758003c.png)
![Screenshot (22)](https://user-images.githubusercontent.com/47842161/94474814-5dabf600-01f8-11eb-8f31-4daca824d99c.png)
led 64*32  chain 4 
When I run video-viewer, the LED panel does not display.
![120267576_2702949033366175_5454667049621504465_n](https://user-images.githubusercontent.com/47842161/94475095-cabf8b80-01f8-11eb-87b1-3427efafc93a.jpg)

**Comment by 6010110254** [comment]
Help me pleas @hzeller

**Comment by hzeller** [comment]
You didn't say how you connect your pi, but it looks like from the picture in the background it is an Adafruit Hat.

Did you provide the [`--led-gpio-mapping=adafruit-hat`](https://github.com/hzeller/rpi-rgb-led-matrix#changing-parameters-via-command-line-flags) option to switch to that output mapping ?

**Comment by 6010110254** [comment]
I have --led-gpio-mapping = adafruit-hat     
using
HARDWARE_DESC = adafruit-hat make

Which when I run Image Viewer  ->  sudo ./led-image-viewer I can run it, work normally.
![image](https://user-images.githubusercontent.com/47842161/94720802-2156d200-037f-11eb-9233-6bd6196def7e.png)

**Comment by 6010110254** [comment]
Is there a 3-step process for running a video?
1.
sudo ./video-viewer  myvideo.webm
2.
./video-viewer  myvideo.webm -O / tmp / vid.stream
3.
sudo ./led-image-viewer  /tmp/vid.stream

**Comment by hzeller** [comment]
I would always provide the `--led-gpio-mapping=adafruit-hat` option on the command line, that way you are sure that you're using it. Otherwise you have to always give the `HARDWARE_DESC` compile time option, e.g. when you compile the video viewer.

These are two ways to watch a video:

 * can run a video directly (one step) with `sudo ./video-viewer ...`
 * You can pre-compute the video to a stream (`video-viewer -O ...`) and watch with led-image-viewer (a two step process, but the first step you only have to do once).

Given that the decoding of a video uses more resources, you get better quality when doing it the pre-computing way.

Also, if you want the best possible quality, I also strongly suggest to do the [PWM modification](https://github.com/hzeller/rpi-rgb-led-matrix#improving-flicker) on the HAT.
