### ISSUE TITLE
help with animation in python binding

### ISSUE THREAD

**Issue by carmonkeylab** [hzeller/rpi-rgb-led-matrix#1167]
hi guys, i successfully finished animation a simple character walking animation on a 64x64 matrix that was 8 frames. when i put the program all together, the program was 32824 lines and took about 5-10 seconds to save. it also took about 5 secs for the program to start. what would be a good way to decrease the line count and cleanup the code. 

i don't know why anyone would want to look at the code but if you want to it is here https://hatebin.com/hrmdadyvoz

**Comment by robgyiv** [comment]
The code is always helpful to share for questions like this, so thanks. I'm not sure that it's all been included in the link you shared, though - it's 983 lines.

From looking at what's there, it looks like you reduce the line count by using [for loops](https://wiki.python.org/moin/ForLoop). So that might be worth trying first.

For the performance, the Python binding will always run slower as is mentioned in the [docs](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python#performance). It might be faster to run if you instead used a series 64x64 pixel images rather than drawing the pixels one by one - but I haven't tested this. There are examples for [using images](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/samples/image-viewer.py) in the samples directory that will be a good reference.
