### ISSUE TITLE
Adafruit bonnet & 32x64- only half the panel is working?

### ISSUE THREAD

**Issue by Tavros613** [hzeller/rpi-rgb-led-matrix#1223]
I have a 32x64 panel and an adafruit bonnet, when I try any of the demos only half of the panel lights up (and it's every two rows). I'm not sure if I'm missing something here, but this has me stumped. 
![B3B4E013-52CB-4CD6-99FB-415ED1E96BBE](https://user-images.githubusercontent.com/10858017/103440996-9ce34c00-4c18-11eb-80fe-3d134419b324.jpeg)

**Comment by hzeller** [comment]
Check out the corresponding topic in the README for this: https://github.com/hzeller/rpi-rgb-led-matrix#64x64-with-e-line-on-adafruit-hatbonnet
You need to add some hardware mod to your Adafruit board.

**Comment by davemaster** [comment]
try with --led-multiplexing= x, where x is a value according your RGB panels, in the help you can find that

**Comment by Tavros613** [comment]
> Check out the corresponding topic in the README for this: https://github.com/hzeller/rpi-rgb-led-matrix#64x64-with-e-line-on-adafruit-hatbonnet
> You need to add some hardware mod to your Adafruit board.

This isn't a 64x64 board is my confusion?

**Comment by hzeller** [comment]
Oh I see, it is only 32 high. In that case what @davemaster said is something to check for: the led-multiplexing values, go through all of them to see if it makes a difference.

If you see that the visible rows somehow overlay (showing the things of the dark rows; not really visible in the chosen example above, try the rotating `-D0` square), then there might also be a problem with an address line; but since you have a premade Adafruit board, that might be somewhat unlikely. Could still be the ribbon-cable though.

**Comment by Tavros613** [comment]
I have two LED boards and it happens the same on each with two different cables. My only remaining thought is it's either the PI or the bonnet?
