### ISSUE TITLE
I have a Issue with displaying a Gif or a Image.

### ISSUE THREAD

**Issue by OskarGER05** [hzeller/rpi-rgb-led-matrix#1338]
The Gif or Image is doubled in diffrent colors than the original one and it is cut in half.
![20210915_162000](https://user-images.githubusercontent.com/71186734/133451656-bafebdd4-ab93-4f96-8fa3-d0acdf6fe468.jpg)
I run the command: sudo ./led-image-viewer Pikachu.gif
it said: Size: 32x32, Hardware gpio mapping: regular
I am using a Joy-It 64x64 LED-Matrix panel

Sorry if my english isn't that good.

**Comment by OskarGER05** [comment]
The Demo works completly fine... i am a bit confused

**Comment by hzeller** [comment]
You have a 64x64 panel, so make sure to supply `--led-rows=64 --led-cols=64` flags.

Since there are many types of displays, you have to go through the [types of display](https://github.com/hzeller/rpi-rgb-led-matrix#types-of-displays) section in the readme to experiment if you also have to need some multiplexing option.

**Comment by OskarGER05** [comment]
ok thank you i will try that out
