### ISSUE TITLE
running ./image-example with different gpio doesnt work

### ISSUE THREAD

**Issue by Steveraws** [hzeller/rpi-rgb-led-matrix#1444]
for my project i use a self made bonnet board. this is i because the use of other features on the raspberry pi 4

i changed the gpio of the regular hardware mapping in hardware-mapping.c and compile and rebuild it

when i do on my own board
`sudo ./demo --led-rows=64 --led-cols=128 --led-row-addr-type=0 --led-slowdown-gpio=4 --led-multiplexing=1 -D 4 runtext.ppm`

i can test all the demo's except demo 3 (image example)
![image](https://user-images.githubusercontent.com/91490656/177308627-110e6ac1-861b-4109-af61-d6403f2b94a2.png)

when i do
`sudo ./image-example --led-rows=64  --led-cols=128 --led-row-addr-type=0 --led-slowdown-gpio=4 --led-multiplexing=1 verkeerslicht.ppm `

i got no image.

when i test this on my adafruit bonnet it works
![IMG20220705121053](https://user-images.githubusercontent.com/91490656/177305853-5724e0b9-ddfe-4333-9e7f-3f0e1186a27e.jpg)

i suspect that the problem lies somewere at the gpio mapping of the image viewing example (something i confirmed with a logic analyser)

is there a way i can excess the gpio mapping of the image viewing example or is the problem somewhere else?

**Comment by hzeller** [comment]
Not sure what version of the library you are using, as the adafruit bonnet would only work if you acually gave the parameter `--led-gpio-mapping=adafruit-hat` (but if you downloaded it from Adafruit, I think they change the Makefile to choose their hat by default or modified the demo).

Anyway, always make sure to give the command line flag `--led-gpio-mapping=...` flag with the name of the hardware mapping you modified (the `.name` part in the `hardware-mapping.c`). (or pre-set the value in your code in the `RGBMatrix::Options` before calling `rgb_matrix::ParseOptionsFromFlags`).

**Comment by Steveraws** [comment]
Hey @hzeller thx for your reply
 im using the current version of this github libary
i modifier the .name  = "regular

`  .name          = "regular",

    .output_enable = GPIO_BIT(5),
    .clock         = GPIO_BIT(4),
    .strobe        = GPIO_BIT(19),

    /* Address lines */
    .a             = GPIO_BIT(17),
    .b             = GPIO_BIT(27),
    .c             = GPIO_BIT(22),
    .d             = GPIO_BIT(6),
    .e             = GPIO_BIT(13),  

    /* Parallel chain 0, RGB for both sub-panels */
    .p0_r1         = GPIO_BIT(18),  
    .p0_g1         = GPIO_BIT(23),  
    .p0_b1         = GPIO_BIT(24),   
    .p0_r2         = GPIO_BIT(25),   
    .p0_g2         = GPIO_BIT(16),   
    .p0_b2         = GPIO_BIT(12),  
  },
`
i compiled it and leave the mapping open because default is regular.

i have it working with the modified gpio in  ./demo runtext.ppm  in examples-api-use 
but when im using the ./image-example with the modified gpio it doesnt work

**Comment by hzeller** [comment]
The default value is what the value of `HARDWARE_DESC` is in lib/Makefile (or if it is set at compile time). I was surprised that you said it worked with the Adafruit HAT, because in that case you'd need to give the extra `--led-gpio-mapping=adafruit-hat` command line option; if not, then this indicated that the compiled-in version was `adafruit-hat` already.

But if you have re-compiled the image-example with your modified hardware mapping, it should work. Does the `utils/led-image-viewer` work ?

(one thing I noticed: you moved output_enable to GPIO 5. This disables hardware pulse generation. In order to make use of the exact hardware timing I strongly suggest to move it to GPIO 18 or GPIO 12. Otherwise the timing relies on 'sleep()' and you get random output brightness glitches of single lines).

**Comment by hzeller** [comment]
ah, the Makefile was not picking up the change in the library. Fixed in https://github.com/hzeller/rpi-rgb-led-matrix/commit/5e3fb5f9fdc3d1f41e21dd4f46fa6bff0218d13a
