### ISSUE TITLE
Question: If you only display static images is a Pi really necessary?

### ISSUE THREAD

**Issue by Boerny41** [hzeller/rpi-rgb-led-matrix#1446]
I've build this matrix a long time ago and it is working well. However since I needed a Pi for quite some time now and don't want to pay 130€ I was thinking if I can replace the one used for the matrix with an esp.

IIRC the matrix gets updated many times per second even if the image shown is static. Obviously this can't be done with an esp but could the code be altern to make the matrix behave like a simple LED strip? 

An esp should be capable of telling all the LEDs their rgb value once when the matrix is turned on/the image is changed and if the matrix would be able to "hold" this image instead of updating it X times per second there wouldn't be any need for the computing power of a Raspberry Pi, right?

Edit: just noticed that I kept talking about esp here. For me any cheap microcontroller like the Pi pico would be fine as well. I just want to use the RPi4 elsewhere^^

**Comment by hzeller** [comment]
The matrix is not smart; unlike the LED strips, you can't tell each pixel its color just once.

  * The only thing the matrix understands if an LED is on or off. And that is decided for a whole row of LEDs. So in order to get color-shades, you need to clock in each row multiple times with different LEDs selected and on-times to get the grayscale.
  * There are only two rows at once that can be addressed, the others are dark. So the driving circuit has to go through all of these one after another and repeat.

So you do need something that constantly clocks in data many million times a second even with a simple static image. Also, I think people have done it with an ESP, but maybe only with one panel, otherwise things slow down too much.
Of course, this could be simplified, you can use an FPGA and some RAM to do the same thing.
