### ISSUE TITLE
p10 1/4 scan led pattern 

### ISSUE THREAD

**Issue by parvsonu** [hzeller/rpi-rgb-led-matrix#1743]
Hello Mr .hzeller,
I have p10 matrix 1/4 scan with three address lines A B C (d line is ground) when i set pixel on and off all pixel are glowing but not as per the coordinate for example 0,0 glow 5,0 ,0 1 glows 6,0
 I have used parameter multiplexing 4 rows 16 col 32 chain 2 parallel 2 However with same parameter my previous matrix was working but D line was not connected to ground
I need your support on this 
![vlcsnap-2024-12-18-14h58m29s967](https://github.com/user-attachments/assets/a524d11a-3909-422c-8d90-43ca62c1c04a)
![vlcsnap-2024-12-18-14h58m13s353](https://github.com/user-attachments/assets/f95bdc11-b2e0-4719-a82b-685825064792)

**Comment by marcmerlin** [comment]
please look at https://rpi-rgb-led-matrix.discourse.group/t/p10rgb-3535-4s-zaggiz-1-4scan-abc-p10-panels-and-https-github-com-2dom-pxmatrix/921
I assume your issue is similar, some 1/4 scan panels have weird pixel mappings that are not supported by this library and will not be unless someone like you submits a code patch to support them.
See the thread I linked, they should work with https://github.com/2dom/PxMatrix 
￼

**Comment by board707** [comment]
@parvsonu 
Please show a good picture of the panel rear side.

**Comment by parvsonu** [comment]
Dear hzeller this is the connection pattern of led if you can provide any
resolution it will be Regards

**Comment by marcmerlin** [comment]
@parvsonu my previous comment still stands. Henner is not going to add support for a random and ever growing list of panels with non standard addressing.
If you want to write the support yourself, or pay someone to do it for you and contribute the code back for it to be merged, this will however likely be accepted.

In the meantime, again, please look at https://github.com/2dom/PxMatrix
