### ISSUE TITLE
 running automatic program

### ISSUE THREAD

**Issue by salvio95** [hzeller/rpi-rgb-led-matrix#223]
Hello how can I start the program automatically when the raspberry has been turned on ?
THANKS FOR THE WORK YOU ARE CARRYING!
regards. Salvio

**Comment by hzeller** [comment]
The very simplest way is to put it in `/etc/rc.local`. This is a script file that is executed on startup.

Make sure to give absolute paths to all files you mention because you can't really make assumptions of the working directory. So something like this would be a good entry:
```
/home/pi/rpi-rgb-led-matrix/utils/led-image-viewer --led-daemon /home/pi/nyan.gif
```

This is the simplest. More advanced way to write a so-called 'init-script' or add it to systemd.

**Comment by salvio95** [comment]
hzeller thank you so much.
Salvio
