### ISSUE TITLE
Best setting for 768x32 display with RPI3

### ISSUE THREAD

**Issue by luis-ordering** [hzeller/rpi-rgb-led-matrix#349]
Hello,

I have a 768x32 (modules indoor P4) screen to show images, my idea is to show this image:

![_curdown](https://user-images.githubusercontent.com/22006877/28002057-2f7481c2-64f7-11e7-8250-ccd10e222ab7.png)

2 times, as if they were two 192x64 screens, then what I do is divide the image and organize it as I need it.

![result](https://user-images.githubusercontent.com/22006877/28002064-4271ce24-64f7-11e7-8e85-2bf1f992362c.png)

Right now it's working, my problem is that it uses 99% CPU, so if I execute any additional tasks, the screen starts blinking.

I want to know if I am doing something wrong, or you can not do anything with a raspberry pi 3, the code I use to display the image is:

`sudo /home/pi/rpi-rgb-led-matrix/utils/led-image-viewer image.png --led-rows=32 --led-chain=24 --led-brightness=80`
 
Thanks for your help.

**Comment by hzeller** [comment]
Yeah, a LED chain of 24 is pushing it.

You really should divide your screen into three sections; you can drive three chains in parallel. The [active adapter](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/active-3) has three outputs, use it.

Running parallel chains does not cost more CPU than a single chain, but longer chains does.
So with three parallel chains, each would only be 8 long, which is much more manageable.

There are a few tips in the README that tell you what affects refresh speed. If your image is limited color like this, I'd for instance try to start using less bits with `--led-pwm-bits` (but it also means that you have less brightness control). Though setting it too low will increase CPU.

Instead of modifying the image, it might be easier to actually write a transformer that then presents the display to be a 192x64 screen and use that.

You don't really want to execute other heavy task on that Pi - it is busy doing the LED refresh. The problem is, even though it is running on a separate core (I suppose you did the `isolcpus` configuration), it is still affected by memory accesses from other programs. Even running `top` makes the display slightly flicker whenever it updates its stats.
So try to minimize any other activity on that Pi, don't run a UI, run the recommended Raspbian Lite etc.
