### ISSUE TITLE
Accuracy "--led-show-refresh" when using gifs with ./led-image-viewer 

### ISSUE THREAD

**Issue by chrisoutwright** [hzeller/rpi-rgb-led-matrix#351]
I have a question about the perception of the refresh rate vs use of mobile camera (using shutter speed to check refresh, 1/30 should correspond to the human eye?).

I noticed that although when it says 300 hz on the console with ./led-image-viewer , filming the animated gif displayed nearly always results in horiontal/diagonal lower brightness bars.

It doesn't disturbes one impression with the great workings of this code and the display but I still would be grateful if one could film the animations with less refreshing effects.

Is this a normal phenomenon when filming when the refresh rate actually is high enough, or is the console estimation not the true refresh rate? 

The more white is used in the gif animated the more pronounced it seems with a camera or manually by looking at the surrounding illumination where the light of the led panel bounces off (brightness flicker, though not noticable when looking directly at the panel). It seems to be persistent even when having 300 hz. 

Setting a specific refresh rate as multiple of the frame rate seems not to change this phenomenon directly.

My settings are `--led-rows 64 --led-chain 4  --led-slowdown-gpio=2 --led-swap-green-blue --led-show-refresh --led-pwm-lsb-nanoseconds 50  --led-parallel=2 --led-pwm-bits=8`

Here the video 120 hz (via `--led-pwm-lsb-nanoseconds 130`) [sample](https://drive.google.com/open?id=0B3r3oSiC8UONOU1vWFpRM2tZSmc)

Here 300 hz when optimizing the settings (like `--led-pwm-lsb-nanoseconds 50` and  lower pwm-bits) [sample](https://drive.google.com/open?id=0B3r3oSiC8UONaWJlSUVlQV9GNUE)

Thank you!

**Comment by hzeller** [comment]
The console output is the true refresh rate as it is measured. But remember that this is scanning through all the lines. If it says 120Hz, it refreshes the whole image 120 times/second, but much faster it goes through the rows.

If you watch it with a camera, you need to make sure that it at least has 1/120 second of exposure time, otherwise you only capture part of the illumination and see bands or flicker; it is the same issue that you have if you want to film any TV screen with too short exposure - you see bands going through it. A typical time aliasing issue.

Given that the LEDs are so bright, you see more flicker with a camera when it is white: the camera tries to compensate by having a shorter exposure time which is then below 1/120s. If you have a camera with controls, you can fix that by closing the aperture. If not, try to film it through a heavily tinted glass.
