### ISSUE TITLE
Piping a single random .gif from folder to led-image-viewer

### ISSUE THREAD

**Issue by p3ltsi** [hzeller/rpi-rgb-led-matrix#396]
I have a RPi2 which has all sorts of stuff behind it and one is a pair of chinese RGB LED matrixes. I'm using led-image-viewer to draw one random animated gif to them, but I can't wrap my head around why these bash commands don't work as intended.

```
sudo ./led-image-viewer -C --led-chain=2 --led-brightness=20 -l 1 | find /home/pi/rpi-rgb-led-matrix/utils/*.gif -type f | shuf -n 1
/home/pi/rpi-rgb-led-matrix/utils/9.gif
Expected image filename.

sudo ./led-image-viewer -C --led-chain=2 --led-brightness=20 | shuf -en 5 /home/pi/rpi-rgb-led-matrix/utils/*.gif -n 1
/home/pi/rpi-rgb-led-matrix/utils/12.gif
Expected image filename.
```

Both produce the random .gif from that folder, but there's a line break or something messing things up.

**Comment by hzeller** [comment]
What you are doing in the shell doesn't make any sense: you start led-image-viewer and pipe _its 
 output_ to a command-line that attempts to find a random element.

What you want is [command substituion with its output.](http://tldp.org/LDP/abs/html/commandsub.html). This is very common and needed everywhere, so it is good to familiarize yourself with it. Please read the bash manual.

So what you want to do is to have that command-line return some list of files (or a random file) and then use that as input for the command, e.g. with back-ticks. Also, why do you use `find` in combination with `shuf` if you can use `shuf` directly with the `-e` option ?

```
   sudo ./led-image-viewer  `shuf -e -n1 /home/pi/rpi-rgb-led-matrix/utils/*.gif`
```

Instead of backticks, you can use the `$()` way to express this

```
  sudo ./led-image-viewer $(shuf -e -n1 /home/pi/rpi-rgb-led-matrix/utils/*.gif)
```
(BTW, led-image-viewer has a mode in which you can give it a set of files and go through them forever, shuffling along the way, which might already do what you need without extra things:
```
  sudo ./led-image-viewer -w5 -f -s /home/pi/rpi-rgb-led-matrix/utils/*.gif
```
)
