### ISSUE TITLE
P5 64x32 16S 

### ISSUE THREAD

**Issue by HummingBuddha** [hzeller/rpi-rgb-led-matrix#485]
Hello HZeller

Thanks for solving P5 32x32 8S (#66). I am having the same issue with P5 64x32 16S in parallel mode. I have even updated my rgb-matrix and Flaschen-Taschen but still I am having the issue. I am giving
server fields as sudo ./ft-server  --led-rows=32 --led-cols=64 -D64x64 --led-parallel=2 
and 
client fields as ./send-text -h localhost "  " -f fonts/10x20.bdf -s 0 -g 64x64+0+0+1
I have attached the images for your reference. Please let me know your inputs or should i need to write any transformer or modify the existing transformer.
![img_20180122_165630](https://user-images.githubusercontent.com/31981475/35221088-df9fb84a-ff9e-11e7-81fc-a832bc0f4ca5.jpg)

![img_20180122_171533](https://user-images.githubusercontent.com/31981475/35220616-197e1f86-ff9d-11e7-9f7f-a9aaa7065a63.jpg)

**Comment by hzeller** [comment]
It is hard to tell, in particular as this only uses the top-half of the display.
Can you run the [demo from this project with -D3 (simple square)](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#running-some-demos), which makes things a little easier to see ?

Do you have a picture of the IDC connector on the back of the panel to see the markings ? It might help to figure out what flavor that is.

Did you wire these panels yourself or are you using an [adapter]( https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/adapter/active-3) ? If you wired it yourself, double-check the address lines [A, B, C, D].

**Comment by HummingBuddha** [comment]
Hello HZeller

Tried with D3 demo and have attached the images. 
Image:1 Single Panel, 
![single panel](https://user-images.githubusercontent.com/31981475/35261188-1b3e4b46-0035-11e8-9ef1-3d4c999388b3.jpg)

Image2: With parallel & without Chain
![parallel without chain](https://user-images.githubusercontent.com/31981475/35261192-23b1782a-0035-11e8-97b7-12c626a5365a.jpg)

Image3: With parallel=2 & chain=2
![with parallel chain](https://user-images.githubusercontent.com/31981475/35261200-27426846-0035-11e8-94ce-5210e1ae6879.jpg)

Image4:The IDC 
![idc](https://user-images.githubusercontent.com/31981475/35261203-29e21416-0035-11e8-8626-bf325f3d45d2.jpg)

Image5:A,B,C,D lines
![a b c d lines](https://user-images.githubusercontent.com/31981475/35261207-2d9785f0-0035-11e8-9e21-9860f216a8b7.jpg)

Image6:P5-64x32-16S
![p5-64x32-16s](https://user-images.githubusercontent.com/31981475/35261212-3037c91e-0035-11e8-8874-9fb18e63e675.jpg)


Wiring is done by me, I havent used any adapters as such. Have checked the A,B,C,D lines and all are looking great. 
Hope these might help you to help me. 

Thanks for your support.

**Comment by hzeller** [comment]
So looks like the address decoding in the bottom half of the bottom board is not working.

It is not your wiring, because then this would happen in the top and bottom half of that board, as the A, B, C, D are shared between the top and bottom half of each board. The fact that it only shows up on one of these means that it is not the wiring to the matrix but that the matrix itself is faulty. Nothing we can work around in software.

You can double-check if you make the bottom board the top board, then the same artifact will show up in the top board (that tells you that it is not the second parallel line, but just the top issue).

 I suspect they have a solder short there somewhere in some address decoder, you might maybe find something if you closely inspect all the chips they have on there. It could also be a faulty address decoder chip.

**Comment by hzeller** [comment]
Another thought: do you level convert the 3.3V logic level to 5V for the matrix board ? Some boards really want 5V logic levels, so if no conversion took place, it is possible to see such artifacts.

You might be able to see if that is the case by reducing the voltage on the board to, say 3.5V - 4V and see if it starts working (the colors will be off, as it can't switch on all the LEDs, in particular blue, but this is only for experimenting).
