### ISSUE TITLE
New Resistor on PCB

### ISSUE THREAD

**Issue by squeegiefreak** [hzeller/rpi-rgb-led-matrix#54]
I was looking at the new master active 3 adapter boards, and I noticed there is now a 10k resistor from the experimental boards. Is this just a pull up resistor? Thanks.

**Comment by hzeller** [comment]
Yes. It makes sure that the OE line is high on bootup, otherwise random rows might light up very brightly at bootup time (or shutdown time) - which I fear could damage the panels because at that time no line switching happens.

The Pi has an internal pulldown of about 50k, so with a 10k pullup I can overcome that and make sure that the input is considered 'high' when not driven.

You can manually add this resistor between pin 1 (3.3V) and pin 12 (the 6th pin on the right).
