### ISSUE TITLE
How do I go about scrolling negative numbers using scrolling-text-example.cc?

### ISSUE THREAD

**Issue by D9X6** [hzeller/rpi-rgb-led-matrix#644]
When I try to scroll "-300"
```
sudo ./scrolling-text-example -f ../fonts/9x18B.bdf -300
```

It creates this error:
```
./scrolling-text-example: invalid option -- '3'
usage: ./scrolling-text-example [options] <text>
Takes text and scrolls it with speed -s

```

**Comment by D9X6** [comment]
Awesome! Thanks a lot @hzeller 👍 
I had a feeling it had something to do with the flags, just didn't know how to go about Googling the issue.
I'll be sure to give that link a read. Thanks again!

**Comment by D9X6** [comment]
Hey @hzeller, how do I separate dollar signs?

I've tried "-$300" and "--$300" but it doesn't work.

**Comment by ajxn** [comment]
Look up how to quote arguments and what special characters there are in
shell command line. You might want to try "man bash" to get that, or just
Google it.

The $ character is used to get value from shell variables. Quote it with \$
or with '-character, like '$300'.


Den 23 juni 2018 10:45 skrev "D9X6" <notifications@github.com>:

Hey @hzeller <https://github.com/hzeller>, how do I separate dollar signs?

I've tried "-$300" and "--$300" but it doesn't work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hzeller/rpi-rgb-led-matrix/issues/644#issuecomment-399653734>,
or mute the thread

**Comment by hzeller** [comment]
You really should just just implement the text scrolling directly in Python, that saves you a lot of headache with invoking some external binary.
