### ISSUE TITLE
Cube Arrangement

### ISSUE THREAD

**Issue by werling** [hzeller/rpi-rgb-led-matrix#674]
Hello!

First of all a big thank you to you and the people who help you! rpi-rgb-led-matrix and flaschentaschen are great projects.

Here is my project:
I'd like to build a led cube with 5 32x32  led modules. Arranged like this:

![20180729_1416272](https://user-images.githubusercontent.com/22643656/43366281-6e021f08-933b-11e8-89b7-49f2fe4d1e24.jpg)

I'd like to use a 96x96 canvas to display stuff. And to make it easier I'd like to arrange the led panels virtually like this:
![20180729_14162723](https://user-images.githubusercontent.com/22643656/43366296-cba6d432-933b-11e8-8cd6-b867ebd182a9.jpg)

Module 1, 3, 7 and 8 are only virtual.

So my question is:
Is it possible to configure panel 2  and 8 to display the images of the second panel in the chain? 
Or what is the best way to to this?

**Comment by hzeller** [comment]
Look at #661 there is a very similar question.

Since you have to three parallel chains, I suggest to arrange the boards more evenly so that each chain only has two panels. Thus, you don't need to run with `--led-chain=3` but only `--led-chain=2`; thus your refresh rate is higher. Since you need to do anyway mapping of these panels in software, it doesn't really matter how they are connected.

What I would suggest is to implement  a [`Canvas`](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/include/canvas.h#L21) that pretends to be a single 32x32 canvas. But the implementation receives SetPixel(), and then just calls SetPixel() on the mirrored boards (whose position you can calculate with simple adding multiple of 32 for x and y. So whenever you use that Canvas, it automatically sets all the multiple places.
