### ISSUE TITLE
6 panels 32 X 192, slight ghosting

### ISSUE THREAD

**Issue by coulix** [hzeller/rpi-rgb-led-matrix#691]
Hello ~

- Latest Raspberry 3
- 200hz

Everything is working mostly great out of the box, thank you for your efforts on this great project 👍

Using 6 chained panels I am seing a bit of ghosting or misaligned pixels on the text demo when the text is moving. For example the `L` is flickering a bit on its edge when moving.

On panel 1 it is perfect then it gets a bit worst toward the end of the chain. 

Is there anything I can do to improve that ? I tried several parameters like pwm, interlace mode without success.

Video:
[matrix_led_ghosting_video.zip](https://github.com/hzeller/rpi-rgb-led-matrix/files/2385576/matrix_led_ghosting_video.zip):

![image](https://user-images.githubusercontent.com/26057/45585017-a7f5ff00-b8dd-11e8-919e-e48254b6a6c7.png)

**Comment by hzeller** [comment]
Depending on the panels, they might not have a proper delay for the clock signal when they output the signal on the output side. This might lead to the clock not aligned with the data anymore.

What you could try is to increase the slowdown gpio parameter to see if this changes things.

In general, it is probably a good idea to not have all panels in one long chain, but use three parallel chains with 64 pixels each, then remap the pixels so that you have the same physical layout. That way, you have the shortest possible chain and higher refresh rate but you have to [write a pixel-mapper](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#writing-your-own-mappers) to have your physical (from the connections) 64x96 panel look like a logical 192x32.
