### ISSUE TITLE
Vertical Image Scroller

### ISSUE THREAD

**Issue by lbnshrivas** [hzeller/rpi-rgb-led-matrix#742]
Hi All,

Has anyone implemented the vertical image scroller for .jpg and .png image files.
I was going through the led-image-viewer.cc code and have found that in _**LoadImageAndScale()**_ method, under comments its being mentioned that **fill_width** and **fill_height** variables are being used for scrolling the image but I couldn't figure out much that how these variable can help in scrolling an image.

Can anyone please help me in this regard.

Would highly appreciate your cooperation.

Thanks in Advance...!!!

**Comment by hzeller** [comment]
The code you found is there to make sure to fit the image to the full width or full height, so that scrolling looks good.

I think I once had scrolling in the led-image-viewers or prepared for it, but currently, implementing scrolling is a little more involved as the animations are all stored in a StreamReader which allows to minimize the runtime effort needed to display the data and to also create offline streams of the same thing, but it also means that for scrolling you
  (a) either store the whole scroll of the image as single animation (which would work, but it means a lot of memory used, as it is pre-calculated). You would do that by creating an image_sequence out of a single image by scrolling it the way you'd like it to, then let the rest of the system take care of it.
  (b) have a second code-path that does that scrolling on-the-fly while displaying.

**Comment by lbnshrivas** [comment]
Not needed anymore.
