### ISSUE TITLE
16-panel LED chain

### ISSUE THREAD

**Issue by jayeheffernan** [hzeller/rpi-rgb-led-matrix#913]
We're looking at a deployment of 16 small (16x32) LED panels in a chain.  The README implies that this should theoretically be fine, but that there may be some "timing problems".  Could you elaborate a little on this?  Do you imagine there'll be noticeable issues on a chain of this length? 
 What exactly should we be looking out for?

Thanks!

**Comment by hzeller** [comment]
The internal structure of these panels is a long shift-register, so there is clock and data. The outcoming data of one stage is the input to the next stage. Inevitably, there are delays from stage to stage, but if all stages are connected to the same clock, later bits in the chain might come too late. If you have 16 panels with 32 pixels each, this means that after a delay of 512 shift-register stages, things should still be aligned within the clock period (which is in the 20Mhz range), which means the delay should be less than 0.1ns (50 ns / 512).

Now, the panels _should_ compensate for that by having the output clock also delayed according to the expected data delay, but that might depend on the construction of the panel etc. But even then, inaccuracies can add up over 16 panels.

So if the panels are not doing compensation, what you'd see is that later in the chain, you see vertical lines glitching right and left, or that vertical lines are missing. Hard to tell exactly as it really depends on the panel, but something like that. You might be able to compensate for that with a higher gpio-slowdown value.

(Having said that, I have successfully tested this with 12 panels in a row and it worked (most panels I had at the time)).

The refresh rate will go down; so you should try (even before you have the panels connected) to test what output frequency you'd get (use the `--led-refresh` flag and supply all the values you need `--led-chain, --led-rows, --led-multiplexing` etc.).

In general, if this is your only chain, you should consider using three parallel chains, each with 6 panels each (which means 18 panels total, but you only use 16), and then do some pixel-mapping so that you can address it as canvas as you need. This reduces the potential problematic effects and increases your refresh rate without any additional CPU cost.
