### ISSUE TITLE
Higher brightness of led modules

### ISSUE THREAD

**Issue by currentlysober** [hzeller/rpi-rgb-led-matrix#94]
Dear Henner,

from the PDF describing the led modules I work with, I know that my modules have brightness up to 7000cd/sqm
However, I cannot make it so bright.
I noticed that after disconnecting panels, when random leds begin to shine, the brightness it much-much higher that during normal work. 
I sent you PDF, maybe there is some extra info which can help to make them shine better.
I was trying to play with those values:

```
static const long kBaseTimeNanos = 250;
canvas->SetPWMBits(X);
```

But there is no visible result - well, maybe there is, but not to have 7000cd/sqm.

Is there any other way to make it shine stronger?
I activated RGB_SLOWDOWN_GPIO to avoid random pixels. But I believe there is some way to higher the brightness. I will be grateful for this information, maybe someone finds it useful too.

Regards
Daniel

**Comment by hzeller** [comment]
The LEDs you see shining bright when nothing is connected is because they are overdriven. They are multiplexed (1:8 or 1:16 typically, depending on the type of display). It is possible to do that, because the LEDs are only on briefly and then quickly switched to the next line (if they would be on for longer, they would burn out in a couple of seconds).
So you see the brightness about 1:8 or 1:16 when an image is displayed which is to be expected.

The software tries to keep the LEDs on as much as possible; it even uses the on-time to stage the next line to be displayed (clocking in in parallel to outputs). For the lower bits, there needs to be a bit of dark time as the displays are not fast enough to accept the data fast enough. You can somewhat influence that with kBaseTimeNanos, but it is probably not visible unless you chain a lot of panels (though your refresh-rate will be affected of course).

The SLOWDOWN option will increase that dark time a bit. Still, this library will keep the panel on over 90% of the time if you display all-white (can be less if you chain a lot of these, as more data needs to be clocked in). The eye wouldn't be able to really distinguish between 90% and 100% though.

(Note, that any number you get from manufacturer is only meant to be in the best possible case; possibly all diodes on white and no dark-time because they measure without clocking in data. Also, they will probably 'round' the values somewhat.)

If you have one panel of 16cmx16cm (a typical size), you'd expect about 180cd (if 7000cd/m^2), so about 180lux in 1m distance.

Anyway, the brightness is probably already close to optimal
